name: msal_js
description: "A Dart wrapper for the 'Microsoft Authentication Library for JavaScript (MSAL.js)'."
version: 3.0.0
homepage: https://github.com/Francessco121/msal-js-dart
repository: https://github.com/Francessco121/msal-js-dart
issue_tracker: https://github.com/Francessco121/msal-js-dart/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.0
